name: eco_manage
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  cloudinary_public: ^0.23.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/Logo/LOGO SiBersih.png
    - assets/splashscreen/SPLASH SCREEN 1.png
    - assets/splashscreen/SPLASH SCREEN 2.png
    - assets/splashscreen/SPLASH SCREEN 3.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logo/LOGO SiBersih.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/Logo/LOGO SiBersih.png"